Repository mthri/dfp-persian, pull requests merged in 2021-10, with the labels that each got.

#66 Structure stuff
  13- Permissions  /README.md
  6- Static Assets/README.md
  README.md
Labels: Structure

#67 Chapter 8
  8- Environment Variables/README.md
  README.md
Labels: First Check

#69 Translate Chapter 16 (CSRF)
  16- Security/README.md
Labels: hacktoberfest-accepted

#72 Ch-3 | README
  3- Bookstore Project /README.md
  README.md
Labels: hacktoberfest-accepted

#80 چیزایی که مونده بود
  README.md
Labels: hacktoberfest-accepted
