Repository mthri/dfp-persian, pull requests merged in 2021-09, with the labels that each got.

#41 first of chapter 15
  15- Performance/README.md
  README.md
Labels: First Check, Second Check

#43 Chapter 8: Environment Variables
  8- Environment Variables/README.md
Labels: First Check

#47 Chapter 3
  3- Bookstore Project /README.md
  LICENSE
Labels: First Check, Second Check

#48 pull request
  1- Docker/README.md
Labels: First Check, Second Check

#50 ch17
  17- Deployment/README.md
Labels: First Check, Second Check

#53 Chapter 17
  17- Deployment/README.md
  17- Deployment/images/1.png
  17- Deployment/images/2.png
  17- Deployment/images/3.png
  17- Deployment/images/4.png
  17- Deployment/images/5.png
Labels: Done, First Check, Second Check

#54 complete the translation of chapter 1
  1- Docker/README.md
Labels: First Check, Second Check

#55 .gitattributes
  .gitattributes
Labels: Technical

#57 Changes | Updates
  8- Environment Variables/README.md
  README.md
Labels: First Check, Second Check

#58 chapter10 full-translation-1
  10- Books App/README.md
  10- Books App/images/1.png
  10- Books App/images/2.png
  10- Books App/images/3.png
  10- Books App/images/4.png
  10- Books App/images/5.png
  10- Books App/images/6.png
  10- Books App/images/7.png
  10- Books App/images/8.png
  10- Books App/images/9.png
Labels: First Check, Second Check

#60 Edited | Done
  10- Books App/README.md
  README.md
Labels: Done, First Check, Second Check
